version: '2'
services:
    template-app:
        image: template
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@template-oracle:1521:template
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
